projects.vkmpart6 = {
  styles: ['mac', 'c64'],
  bodycls: 'c64',
  ui: ['show-key', 'code'],
  emu: 'c64',
  emucls: 'c64',
  use: 'macbook',
  usecls: 'mac',

  sequences: [
    { name: 'left shift', sequence: [
        { code: 'Shift_L 1 7 ????', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: { cls: 'ct'} },
        { code: 'Shift_L 1 7 ????', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: 'hide', flags: 'show' },
        { code: 'Shift_L 1 7 ????', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: 'hide', flags: 2 },
        { code: 'Shift_L 1 7 2', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: 'hide' },
        { emu: [ 'shift', 'cbm' ] },
        { code: 'Control 7 5 0', emu: 'cbm', use: 'control', grid: { cls: 'ct' }, rcode: 'hide' },
        { code: 'Control 7 5 0', emu: 'cbm', use: 'control', grid: { cls: 'ct' }, rcode: 'hide', flags: 8192 },
        { code: 'Shift_L 1 7 2', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: 'hide' },
        { code: 'Shift_L 1 7 2', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: 'hide', flags: 34 },
        { code: 'Shift_L 1 7 34', emu: 'ltshift', use: 'ltshift', rcode: 'hide', grid: 'hide' },
        { code: 'Shift_L 1 7 ????', emu: [ 'shift', 'cbm' ], use: [ 'shift', 'control' ], grid: 'hide', rcode: 'hide' },
        { code: 'Shift_L 1 7 ????', emu: [ 'shift', 'cbm' ], use: [ 'shift', 'control' ], grid: 'hide', rcode: 'hide', flags: 'show' },
        { code: 'Shift_L 1 7 ????', emu: [ 'shift', 'cbm' ], use: [ 'shift', 'control' ], grid: 'hide', rcode: 'hide', flags: 1024 },
        { code: 'Shift_L 1 7 ????', emu: [ 'shift', 'cbm' ], use: [ 'shift', 'control' ], grid: 'hide', rcode: 'hide', flags: 3072 },
        { code: 'Shift_L 1 7 ????', emu: [ 'shift', 'cbm' ], use: [ 'shift', 'control' ], grid: 'hide', rcode: 'hide', flags: 3073 },
        { code: 'Shift_L 1 7 3073', emu: [ 'shift', 'cbm' ], use: [ 'shift', 'control' ], grid: 'hide', rcode: 'hide' },
      ]
    },
    { name: 'fifth row', sequence: [
        { emu: [ 'z', 'x', 'c', 'v', 'b', 'n', 'm' ], use: [ 'z', 'x', 'c', 'v', 'b', 'n', 'm' ] },
        { showKey: 'Z', code: 'z 1 4 32', emu: { key: 'z', cls: 'o-tm3' }, use: 'z' },
        { showKey: 'Z', code: 'z 1 4 32', emu: { key: 'z', cls: 'o-tm3' }, use: 'z', grid: 'hide', rcode: 'hide', flags: 32 },
        { showKey: '&#xe06d;', code: 'z 1 4 3072', emu: [ 'cbm', { key: 'z', cls: 'o-b3l' } ], use: [ 'control', 'z' ] },
        { showKey: '&#xe06d;', code: 'z 1 4 3072', emu: [ 'cbm', { key: 'z', cls: 'o-b3l' } ], use: [ 'control', 'z' ], grid: 'hide', rcode: 'hide', flags: 3072 },
        { showKey: '&#xe05a;', code: 'Z 1 4 1', emu: [ 'shift', { key: 'z', cls: 'o-b3r' } ], use: [ 'shift', 'z' ] },
        { showKey: '&#xe05a;', code: 'Z 1 4 1', emu: [ 'shift', { key: 'z', cls: 'o-b3r' } ], use: [ 'shift', 'z' ], grid: 'hide', rcode: 'hide', flags: 1 },
        { showKey: 'X', code: 'x 2 7 32', emu: { key: 'x', cls: 'o-tm3' }, use: 'x' },
        { showKey: '&#xe07d;', code: 'x 2 7 3072', emu: [ 'cbm', { key: 'x', cls: 'o-b3l' } ], use: [ 'control', 'x' ] },
        { showKey: '&#xe058;', code: 'X 2 7 1', emu: [ 'shift', { key: 'x', cls: 'o-b3r' } ], use: [ 'shift', 'x' ] },
        { showKey: 'C', code: 'c 2 4 32', emu: { key: 'c', cls: 'o-tm3' }, use: 'c' },
        { showKey: '&#xe07c;', code: 'c 2 4 3072', emu: [ 'cbm', { key: 'c', cls: 'o-b3l' } ], use: [ 'control', 'c' ] },
        { showKey: '&#xe043;', code: 'C 2 4 1', emu: [ 'shift', { key: 'c', cls: 'o-b3r' } ], use: [ 'shift', 'c' ] },
        { showKey: 'V', code: 'v 3 7 32', emu: { key: 'v', cls: 'o-tm3' }, use: 'v' },
        { showKey: '&#xe07e;', code: 'v 3 7 3072', emu: [ 'cbm', { key: 'v', cls: 'o-b3l' } ], use: [ 'control', 'v' ] },
        { showKey: '&#xe056;', code: 'V 3 7 1', emu: [ 'shift', { key: 'v', cls: 'o-b3r' } ], use: [ 'shift', 'v' ] },
        { showKey: 'B', code: 'b 3 4 32', emu: { key: 'b', cls: 'o-tm3' }, use: 'b' },
        { showKey: '&#xe07f;', code: 'b 3 4 3072', emu: [ 'cbm', { key: 'b', cls: 'o-b3l' } ], use: [ 'control', 'b' ] },
        { showKey: '&#xe042;', code: 'B 3 4 1', emu: [ 'shift', { key: 'b', cls: 'o-b3r' } ], use: [ 'shift', 'b' ] },
        { showKey: 'N', code: 'n 4 7 32', emu: { key: 'n', cls: 'o-tm3' }, use: 'n' },
        { showKey: '&#xe06a;', code: 'n 4 7 3072', emu: [ 'cbm', { key: 'n', cls: 'o-b3l' } ], use: [ 'control', 'n' ] },
        { showKey: '&#xe04e;', code: 'N 4 7 1', emu: [ 'shift', { key: 'n', cls: 'o-b3r' } ], use: [ 'shift', 'n' ] },
        { showKey: 'M', code: 'm 4 4 32', emu: { key: 'm', cls: 'o-tm3' }, use: 'm' },
        { showKey: '&#xe067;', code: 'm 4 4 3072', emu: [ 'cbm', { key: 'm', cls: 'o-b3l' } ], use: [ 'control', 'm' ] },
        { showKey: '&#xe04d;', code: 'M 4 4 1', emu: [ 'shift', { key: 'm', cls: 'o-b3r' } ], use: [ 'shift', 'm' ] },
        { emu: [ 'comma', 'period', 'slash' ], use: [ 'comma', 'period', 'slash' ] },
        { showKey: ',', code: 'comma 5 7 0', emu: { key: 'comma', cls: 'o-b' }, use: { key: 'comma', cls: 'o-b' } },
        { showKey: '<', code: 'less 5 7 1', emu: { key: 'comma', cls: 'o-t' }, use: { key: 'comma', cls: 'o-t' } },
        { showKey: '.', code: 'period 5 4 0', emu: { key: 'period', cls: 'o-b' }, use: { key: 'period', cls: 'o-b' } },
        { showKey: '>', code: 'greater 5 4 1', emu: { key: 'period', cls: 'o-t' }, use: { key: 'period', cls: 'o-t' } },
        { showKey: '/', code: 'slash 6 7 0', emu: { key: 'slash', cls: 'o-b' }, use: { key: 'slash', cls: 'o-b' } },
        { showKey: '?', code: 'question 6 7 1', emu: { key: 'slash', cls: 'o-t' }, use: { key: 'slash', cls: 'o-t' } },
        { code: 'Shift_R 6 4 ????', emu: 'rtshift', use: 'rtshift', rcode: { act: 'skip', cls: 'lt' } },
        { code: 'Shift_R 6 4 ????', emu: 'rtshift', use: 'rtshift', rcode: 'hide', flags: 4 },
        { code: 'Shift_R 6 4 ????', emu: 'rtshift', use: 'rtshift', rcode: 'hide', flags: 36 },
        { code: 'Shift_R 6 4 36', emu: 'rtshift', use: 'rtshift', rcode: { cls: 'lt' } },
        { code: 'Shift_R 6 4 3073', emu: [ 'cbm', 'rtshift' ], use: [ 'control', 'rtshift' ], grid: 'hide', rcode: { cls: 'lt' } }
      ]
    },
    { name: 'sixth row 1', sequence: [
        { use: 'fn' },
        { code: 'Control_L 7 5 0', emu: 'cbm', use: 'control', grid: { cls: 'ct' } },
        { code: 'Alt_L 7 2 16384', emu: 'ctrl', use: 'ltoption' },
        { code: 'Alt_L 7 2 16384', emu: 'ctrl', use: 'ltoption', grid: 'hide', rcode: 'skip', flags: 16384 },
        { code: 'Meta_L 7 5 8192', emu: 'cbm', use: 'ltcommand' },
        { code: 'Meta_L 7 5 8192', emu: 'cbm', use: 'ltcommand', grid: 'hide', rcode: 'skip', flags: 8192 },
        { code: 'Meta_L 7 5 8192', emu: 'cbm', use: 'ltcommand', grid: 'hide', rcode: 'skip' },
        { use: 'rtcommand' },
        { emu: 'ctrl', use: 'rtoption' },
      ]
    },
    { name: 'sixth row 2', sequence: [
        { code: 'space 7 4 0', emu: 'space', use: 'space' },
        { emu: [ 'right', 'down' ] },
        { code: 'Left 0 2 1', emu: [ 'shift', { key: 'right', cls: 'o-tm3' } ], use: 'left', grid: { cls: 'ct' }, rcode: { cls: 'lt' } },
        { code: 'Up 0 7 1', emu: [ 'shift', { key: 'down', cls: 'o-tm3' } ], use: { key: 'updown', cls: 'o-t' }, grid: { cls: 'ct' }, rcode: { cls: 'lt' } },
        { code: 'Down 0 7 0', emu: { key: 'down', cls: 'o-bm3' }, use: { key: 'updown', cls: 'o-b' }, grid: { cls: 'ct' }, rcode: { cls: 'lt' } },
        { code: 'Right 0 2 0', emu: { key: 'right', cls: 'o-bm3' }, use: 'right', grid: { cls: 'ct' }, rcode: { cls: 'lt' } },
      ]
    },
    { name: 'control codes', sequence: [
        { emu: [ 'ctrl', 'c' ] },
        { emu: { key: 'stop', cls: 'o-b' }, use: 'esc' },
        { emu: [ 'ctrl', 'e' ] },
        { showKey: 's-white|2', emu: [ 'ctrl', { key: '2', cls: 'o-b3' } ], use: [ 'ltoption', '2' ] },
        { emu: [ 'ctrl', 'h' ] },
        { emu: [ 'ctrl', 'i' ] },
        { emu: [ 'ctrl', 'j' ] },
        { emu: [ 'ctrl', 'm' ] },
        { emu: 'return', use: 'return' },
        { emu: [ 'ctrl', 'n' ] },
        { emu: [ 'ctrl', 'q' ] },
        { emu: { key: 'down', cls: 'o-bm3' }, use: { key: 'updown', cls: 'o-b' } },
        { emu: [ 'ctrl', 's' ] },
        { emu: { key: 'home', cls: 'o-b' }, use: [ 'fn', 'f12' ] },
        { emu: [ 'ctrl', 't' ] },
        { emu: { key: 'del', cls: 'o-b' }, use: 'delete' },
        { emu: [ 'ctrl', 'gbp' ] },
        { showKey: 's-red|3', emu: [ 'ctrl', { key: '3', cls: 'o-b3' } ], use: [ 'ltoption', '3' ] },
        { emu: [ 'ctrl', 'semicolon' ] },
        { showKey: 's-green|6', emu: [ 'ctrl', { key: '6', cls: 'o-b3' } ], use: [ 'ltoption', '6' ] },
        { emu: [ 'ctrl', 'h', 'i', 'n' ] },
        { code: 'abovedot 3 5 4096', emu: [ 'ctrl', 'h' ], use: [ 'ltoption', 'h' ] },
        { code: 'abovedot 3 5 4096', emu: [ 'ctrl', 'h' ], use: [ 'ltoption', 'h' ], grid: 'hide', rcode: 'skip', flags: 4096 },
        { code: 'dead_circumflex 4 1 4096', emu: [ 'ctrl', 'i' ], use: [ 'ltoption', 'i' ] },
        { code: 'dead_perispomeni 4 7 4096', emu: [ 'ctrl', 'n' ], use: [ 'ltoption', 'n' ] },
      ]
    }
  ]
}

